name: Build Unsigned IPA

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Build IPA
        run: |
          xcodebuild -project KimiAudio.xcodeproj \
                     -scheme KimiAudio \
                     -configuration Release \
                     -destination 'generic/platform=iOS' \
                     archive \
                     -archivePath build/RAGVoice.xcarchive \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     AD_HOC_CODE_SIGNING_ALLOWED=YES
          xcodebuild -exportArchive \
                     -archivePath build/RAGVoice.xcarchive \
                     -exportPath build \
                     -exportOptionsPlist .github/exportOptions.plist
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: RAGVoice-unsigned
          path: build/RAGVoice.ipa
