name: iOS Demo

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ios-demo.yml'
      - 'example/**'
      - '!example/REAMDE.md'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/ios-demo.yml'
      - 'example/**'
      - '!example/REAMDE.md'

jobs:
  build-demo:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: example

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Run Cocoapods
        run: pod install

      - name: XCode Build
        run: xcodebuild build
          -configuration Debug
          -workspace ios-voice-processor.xcworkspace
          -sdk iphoneos
          -scheme ios-voice-processor-Example
          -destination "platform=iOS Simulator,name=iPhone 12"
          CODE_SIGNING_ALLOWED=NO

